homework 2
mcdimus/MyAndroidAcademyApp pull request #1
Opened 2020-11-22 10:08 UTC by mcdimus

Не осилил три вещи:
1) Иконка для кнопки "Back". Если сгенирировать вектор из svg из figma, получается какая-то крива загогулина.
2) не получилось выровнять звездочки с кол-вом ревью
3) не получилось сделать, чтобы картинки актеров занимали бы все пространство, в горизонтальном режиме особеноо видно

2020-11-23 12:50 UTC, an-yurii commented
За рамками данного ПР.
Использование buildSrc для хранения версий имеет большой недостаток: любое изменение инвалидирует кэш сборки.
![image](https://user-images.githubusercontent.com/31529762/99963977-2e170580-2dc5-11eb-8c02-c84bc473f724.png)

2020-11-23 12:59 UTC, an-yurii commented
Минимальная версия SDK указывает на каких устройствах можно запускать приложение. Ты указал `minSdkVersion(30)`, запустить можно только на Андроид 11. 
Проблема в том, что различные фичи Android SDK доступны только с конкретной версии. Решение, которое опирается на фишки, которые появилиь, например, в SKD 28 (Андроид 9) не подойдет для SDK 23 (Андроид 6).

2020-11-23 13:41 UTC, an-yurii requested changes

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +        android:layout_height="298dp"
```suggestion
        android:layout_height="wrap_content"
```

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Нужно прикрепить все четыре границы к границам `imageView` Верх к верху, низ к низу и так далее.

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +    <Button
Добавить свойство `app:drawableLeftCompat="@drawable/ic_back_btn"`
Макет не родной для Андроид. Иконку можно взять из встроенного набора Андроид студии
![image](https://user-images.githubusercontent.com/31529762/99967415-6f5de400-2dca-11eb-89e1-a8762bf754ff.png)

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +    <androidx.constraintlayout.widget.Guideline
Можно было просто использовать margin

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +    <androidx.constraintlayout.widget.Guideline
Можно было просто использовать margin

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Нужно привязаться к нижнему краю изображения
```
        app:layout_constraintTop_toBottomOf="@+id/imageView" 
        app:layout_constraintBotton_toBottomOf="@+id/imageView" 
```

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +        android:layout_height="0dp"
```suggestion
        android:layout_height="wrap_content"
```

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +        android:layout_marginTop="4dp"
Отступ не нужен

2020-11-23 13:41 UTC, an-yurii commented on app/src/main/res/layout/activity_movie_details.xml
> +        app:layout_constraintTop_toBottomOf="@id/movie_genre" />
Нужно привязаться к `movie_review_counter`
```suggestion
        app:layout_constraintTop_toTopOf="@id/movie_review_counter"
        app:layout_constraintBottom_toBottomOf="@id/movie_review_counter"
        />
```

2020-11-29 15:19 UTC, mcdimus commented
> За рамками данного ПР.
> Использование buildSrc для хранения версий имеет большой недостаток: любое изменение инвалидирует кэш сборки.
> ![image](https://user-images.githubusercontent.com/31529762/99963977-2e170580-2dc5-11eb-8c02-c84bc473f724.png)

2020-11-29 16:13 UTC, mcdimus commented on app/src/main/res/layout/activity_movie_details.xml
> +    <Button
Спасибо, так появилась картинка. Но все равно остается непонятным как изменить расстояние между текстом и иконкой.
А почему не работает `android:drawableStart` и `android:drawablePadding`?

2020-11-29 16:15 UTC, mcdimus commented on app/src/main/res/layout/activity_movie_details.xml
> +    <androidx.constraintlayout.widget.Guideline
Мне наоборот показалось, что вариант с guideline лучше... Есть какие-то существенные минусы у такого подхода?

2020-11-29 16:23 UTC, mcdimus commented on app/src/main/res/layout/activity_movie_details.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Исправил.

2020-11-29 16:23 UTC, mcdimus commented on app/src/main/res/layout/activity_movie_details.xml
> +        app:layout_constraintTop_toTopOf="parent" />
Исправил.

2020-11-29 16:25 UTC, mcdimus commented
Спасибо за комментарии. Стало понятнее как работает `ConstraintLayout`.

Остался один откратый вопрос. Как сделать чтобы картики актерова занимали бы все доступное место в горизонтальном режиме?

2020-12-07 10:40 UTC, merged